version: '3.9'

services:
  server:
    build:
      context: ./apps/server
      dockerfile: ./Dockerfile
    command: ["npm", "run", "dev"]
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ./apps/server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8000:8000'
  client:
    build:
      context: ./apps/client
      dockerfile: ./Dockerfile
    command: ["npm", "run", "dev"]
    depends_on:
      - server
    restart: unless-stopped
    volumes:
      - ./apps/client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5173:5173
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: