version: '3.9'

services:
  server:
    build:
      context: ./apps/server/
      dockerfile: ./Dockerfile
      target: development
    command: npm run start
    env_file:
      - ./apps/server/.env
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8000:8000'
  # client:
  #   container_name: client
  #   build:
  #     context: .
  #     dockerfile: ./apps/client/Dockerfile
  #   restart: unless-stopped
  #   ports:
  #     - 8081:8081
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: